return {
  -- Crystal carries the Gen 2 type table. These are category changes,
  -- not matchup changes.
  types = {
    GHOST = { category = "special" },
    DARK = { category = "physical" },
  },

  moves = {
    ["Barrage"] = { power = 20, accuracy = 100 },
    ["Bind"] = { accuracy = 85 },
    ["Comet Punch"] = { power = 25, accuracy = 100, pp = 25 },
    ["Constrict"] = { power = 40, accuracy = 100, pp = 35 },
    ["Disable"] = { accuracy = 75 },
    ["Dizzy Punch"] = { pp = 20 },
    ["DoubleSlap"] = { power = 20, accuracy = 100, pp = 35 },
    ["ExtremeSpeed"] = { power = 80, accuracy = 100, pp = 10 },
    ["Fury Attack"] = { power = 18, accuracy = 100, pp = 20 },
    ["Fury Swipes"] = { power = 20, accuracy = 100, pp = 20 },
    ["Glare"] = { accuracy = 90, pp = 30 },
    ["Hidden Power"] = { accuracy = 100, pp = 15 },
    ["Mega Kick"] = { accuracy = 85, pp = 10 },
    ["Milk Drink"] = { pp = 5 },
    ["Pay Day"] = { power = 60, accuracy = 100, pp = 20 },
    ["Razor Wind"] = { power = 80, accuracy = 95, pp = 15 },
    ["Recover"] = { pp = 5 },
    ["Scratch"] = { power = 35, accuracy = 100, pp = 35 },
    ["Slam"] = { power = 80, accuracy = 100, pp = 20 },
    ["SonicBoom"] = { accuracy = 100, pp = 20 },
    ["Soft-Boiled"] = { pp = 5 },
    ["Supersonic"] = { accuracy = 70, pp = 20 },
    ["Tackle"] = { power = 35, accuracy = 100, pp = 35 },
    ["Take Down"] = { power = 95, accuracy = 100, pp = 20 },
    ["Tri Attack"] = { power = 85, accuracy = 100, pp = 15 },

    ["Absorb"] = { power = 20, accuracy = 100, pp = 25 },
    ["Egg Bomb"] = { power = 100, accuracy = 100, type = "GRASS", pp = 10 },
    ["Giga Drain"] = { power = 75, accuracy = 100, pp = 15 },
    ["Mega Drain"] = { power = 40, accuracy = 100, pp = 20 },
    ["Vine Whip"] = { power = 40, accuracy = 100, pp = 25 },
    ["Petal Dance"] = { power = 90, accuracy = 100, pp = 20 },

    ["Fire Spin"] = { power = 35, accuracy = 100, pp = 15 },
    ["Flame Wheel"] = { power = 65, accuracy = 100, pp = 25 },
    ["Sacred Fire"] = { pp = 10 },
    ["Sunny Day"] = { pp = 10 },

    ["Clamp"] = { power = 35, accuracy = 100, pp = 10 },
    ["Crabhammer"] = { power = 110, accuracy = 100, pp = 10 },
    ["Hydro Pump"] = { power = 120, accuracy = 85, pp = 10 },
    ["Octazooka"] = { power = 65, accuracy = 100, pp = 15 },
    ["Rain Dance"] = { pp = 10 },
    ["Waterfall"] = {
      power = 70,
      accuracy = 100,
      pp = 15,
      effect = "EFFECT_FLINCH_HIT",
      effectChance = 30,
    },

    ["Cross Chop"] = { power = 100, accuracy = 85, pp = 10 },
    ["DynamicPunch"] = { power = 100, accuracy = 50, pp = 10 },
    ["Hi Jump Kick"] = { power = 120, accuracy = 90, pp = 20 },
    ["Jump Kick"] = { power = 90, accuracy = 95, pp = 25 },
    ["Low Kick"] = { power = 50, accuracy = 100, pp = 20 },
    ["Mach Punch"] = { power = 50, accuracy = 100, pp = 30 },
    ["Rock Smash"] = {
      power = 60,
      accuracy = 100,
      pp = 15,
      effect = "EFFECT_DEFENSE_DOWN_HIT",
      effectChance = 20,
    },
    ["Rolling Kick"] = { power = 60, accuracy = 100, pp = 15 },
    ["Submission"] = { power = 90, accuracy = 100, pp = 25 },
    ["Triple Kick"] = { power = 20, accuracy = 100, pp = 15 },

    ["AncientPower"] = { power = 60, accuracy = 100, pp = 10 },
    ["Rock Slide"] = { power = 80, accuracy = 95, pp = 15 },
    ["Rock Throw"] = { power = 50, accuracy = 95, pp = 25 },

    ["Cut"] = { power = 55, accuracy = 95, pp = 30, type = "BUG", highCrit = true },
    ["Leech Life"] = { power = 40, accuracy = 100, pp = 25 },
    ["Pin Missile"] = { power = 20, accuracy = 100, pp = 30 },
    ["Twineedle"] = { power = 40, accuracy = 100, pp = 20 },

    ["Bone Club"] = { power = 65, accuracy = 100, pp = 20 },
    ["Bone Rush"] = { power = 25, accuracy = 100, pp = 20 },
    ["Bonemerang"] = { power = 50, accuracy = 90, pp = 20 },
    ["Dig"] = { power = 70, accuracy = 100, pp = 20 },
    ["Mud-Slap"] = { power = 20, accuracy = 100, pp = 15 },

    ["Aeroblast"] = { power = 100, accuracy = 95, pp = 10 },
    ["Fly"] = { power = 70, accuracy = 100, pp = 15 },
    -- The document removes Sky Attack's charge turn.  EFFECT_NORMAL_HIT is
    -- the native one-turn route; its dedicated animation remains a
    -- separate engine concern.
    ["Sky Attack"] = {
      power = 120,
      accuracy = 85,
      pp = 10,
      effect = "EFFECT_NORMAL_HIT",
    },

    ["Poison Gas"] = { accuracy = 85, pp = 40 },
    ["Poisonpowder"] = { accuracy = 90, pp = 35 },
    ["Poison Sting"] = { power = 30, accuracy = 100, pp = 35 },
    ["Sludge Bomb"] = { power = 90, accuracy = 100, pp = 15 },
    ["Smog"] = { power = 25, accuracy = 100, pp = 20 },

    ["Future Sight"] = { power = 120, accuracy = 90, pp = 15 },
    ["Psychic"] = { power = 90, accuracy = 100, pp = 15 },
    ["Psywave"] = { accuracy = 95, pp = 15 },
    ["Rest"] = { pp = 5 },

    ["Blizzard"] = { power = 120, accuracy = 85, pp = 5 },
    ["Ice Beam"] = { power = 95, accuracy = 100, pp = 15 },
    ["Icy Wind"] = { power = 65, accuracy = 100, pp = 20 },

    ["Lick"] = { power = 30, accuracy = 100, pp = 30 },
    ["DragonBreath"] = { power = 70, accuracy = 100, pp = 20 },
    ["Twister"] = { power = 70, accuracy = 100, pp = 20 },
    ["Outrage"] = { power = 110, accuracy = 100, pp = 15 },

    ["Iron Tail"] = {
      power = 100,
      accuracy = 90,
      pp = 15,
      effect = "EFFECT_DEFENSE_DOWN_HIT",
      effectChance = 20,
    },
    ["Metal Claw"] = { power = 70, accuracy = 100, pp = 25 },
    ["Spike Cannon"] = { power = 22, accuracy = 100, pp = 15, type = "STEEL" },
    ["Steel Wing"] = { power = 70, accuracy = 100, pp = 25 },

    ["Beat Up"] = { power = 20, accuracy = 100, pp = 10 },
    -- Crystal Legacy documents 101%, which is outside the engine schema.  The
    -- valid equivalent is a guaranteed hit.
    ["Faint Attack"] = { power = 70, accuracy = 100, pp = 20 },
    ["Thief"] = { power = 60, accuracy = 100, pp = 15 },
  },

  pokemon = {
    Ekans = { baseStats = { hp = 40, attack = 65, defense = 44,
      specialAttack = 40, specialDefense = 54, speed = 60 } },
    Arbok = { baseStats = { hp = 62, attack = 95, defense = 69,
      specialAttack = 65, specialDefense = 79, speed = 90 } },
    Pikachu = { baseStats = { hp = 35, attack = 55, defense = 40,
      specialAttack = 50, specialDefense = 50, speed = 90 } },
    Clefable = { baseStats = { hp = 95, attack = 70, defense = 73,
      specialAttack = 95, specialDefense = 90, speed = 60 } },
    Vulpix = { baseStats = { hp = 45, attack = 41, defense = 45,
      specialAttack = 60, specialDefense = 70, speed = 75 } },
    Ninetales = { baseStats = { hp = 78, attack = 71, defense = 80,
      specialAttack = 86, specialDefense = 100, speed = 100 } },
    Wigglytuff = { baseStats = { hp = 140, attack = 70, defense = 55,
      specialAttack = 85, specialDefense = 55, speed = 45 } },
    Oddish = { baseStats = { hp = 50, attack = 50, defense = 55,
      specialAttack = 75, specialDefense = 65, speed = 30 } },
    Gloom = { baseStats = { hp = 70, attack = 65, defense = 70,
      specialAttack = 85, specialDefense = 75, speed = 40 } },
    Vileplume = { baseStats = { hp = 90, attack = 80, defense = 95,
      specialAttack = 100, specialDefense = 90, speed = 50 } },
    Venomoth = { baseStats = { hp = 70, attack = 75, defense = 60,
      specialAttack = 95, specialDefense = 75, speed = 100 } },
    Dugtrio = { baseStats = { hp = 35, attack = 90, defense = 50,
      specialAttack = 50, specialDefense = 70, speed = 120 } },
    Ponyta = { baseStats = { hp = 50, attack = 85, defense = 55,
      specialAttack = 65, specialDefense = 65, speed = 100 } },
    Rapidash = { baseStats = { hp = 65, attack = 100, defense = 70,
      specialAttack = 80, specialDefense = 80, speed = 115 } },
    Dewgong = { baseStats = { hp = 90, attack = 60, defense = 80,
      specialAttack = 80, specialDefense = 95, speed = 70 } },
    Shellder = { baseStats = { hp = 35, attack = 65, defense = 100,
      specialAttack = 45, specialDefense = 25, speed = 40 } },
    Marowak = { baseStats = { hp = 65, attack = 80, defense = 110,
      specialAttack = 50, specialDefense = 80, speed = 45 } },
    Hitmonlee = { baseStats = { hp = 50, attack = 120, defense = 58,
      specialAttack = 35, specialDefense = 110, speed = 87 } },
    Hitmonchan = { baseStats = { hp = 50, attack = 105, defense = 79,
      specialAttack = 35, specialDefense = 110, speed = 81 } },
    Weezing = { baseStats = { hp = 75, attack = 90, defense = 120,
      specialAttack = 85, specialDefense = 70, speed = 60 } },
    Lickitung = { baseStats = { hp = 95, attack = 70, defense = 85,
      specialAttack = 75, specialDefense = 85, speed = 30 } },
    Magmar = { baseStats = { hp = 75, attack = 85, defense = 57,
      specialAttack = 100, specialDefense = 85, speed = 93 } },
    Flareon = { baseStats = { hp = 65, attack = 130, defense = 60,
      specialAttack = 110, specialDefense = 95, speed = 65 } },
    Furret = { baseStats = { hp = 85, attack = 76, defense = 64,
      specialAttack = 55, specialDefense = 55, speed = 90 } },
    Ledian = { baseStats = { hp = 75, attack = 35, defense = 50,
      specialAttack = 55, specialDefense = 110, speed = 85 } },
    Ariados = { baseStats = { hp = 70, attack = 90, defense = 70,
      specialAttack = 70, specialDefense = 70, speed = 80 } },
    Togetic = { baseStats = { hp = 85, attack = 50, defense = 85,
      specialAttack = 80, specialDefense = 105, speed = 40 } },
    Bellossom = { baseStats = { hp = 90, attack = 80, defense = 95,
      specialAttack = 90, specialDefense = 100, speed = 50 } },
    Azumarill = { baseStats = { hp = 100, attack = 50, defense = 80,
      specialAttack = 70, specialDefense = 80, speed = 50 } },
    Sudowoodo = { baseStats = { hp = 80, attack = 100, defense = 115,
      specialAttack = 30, specialDefense = 85, speed = 30 } },
    Yanma = { baseStats = { hp = 75, attack = 105, defense = 65,
      specialAttack = 65, specialDefense = 45, speed = 95 } },
    Aipom = { baseStats = { hp = 70, attack = 90, defense = 65,
      specialAttack = 40, specialDefense = 65, speed = 90 } },
    Quagsire = { baseStats = { hp = 95, attack = 85, defense = 85,
      specialAttack = 75, specialDefense = 75, speed = 35 } },
    Sunflora = { baseStats = { hp = 75, attack = 75, defense = 55,
      specialAttack = 125, specialDefense = 85, speed = 30 } },
    Murkrow = { baseStats = { hp = 70, attack = 105, defense = 52,
      specialAttack = 76, specialDefense = 52, speed = 95 } },
    Misdreavus = { baseStats = { hp = 60, attack = 60, defense = 60,
      specialAttack = 95, specialDefense = 95, speed = 90 } },
    Gligar = { baseStats = { hp = 70, attack = 85, defense = 105,
      specialAttack = 35, specialDefense = 65, speed = 90 } },
    Qwilfish = { baseStats = { hp = 75, attack = 95, defense = 85,
      specialAttack = 65, specialDefense = 75, speed = 85 } },
    Sneasel = { baseStats = { hp = 55, attack = 95, defense = 55,
      specialAttack = 70, specialDefense = 75, speed = 115 } },
    Slugma = { baseStats = { hp = 50, attack = 70, defense = 60,
      specialAttack = 70, specialDefense = 60, speed = 20 } },
    Magcargo = { baseStats = { hp = 60, attack = 80, defense = 130,
      specialAttack = 90, specialDefense = 80, speed = 30 } },
    Swinub = { baseStats = { hp = 80, attack = 65, defense = 40,
      specialAttack = 65, specialDefense = 40, speed = 50 } },
    Piloswine = { baseStats = { hp = 100, attack = 100, defense = 80,
      specialAttack = 80, specialDefense = 70, speed = 50 } },
    Corsola = { baseStats = { hp = 85, attack = 55, defense = 95,
      specialAttack = 65, specialDefense = 95, speed = 35 } },
    Delibird = { baseStats = { hp = 60, attack = 75, defense = 55,
      specialAttack = 85, specialDefense = 45, speed = 80 } },
    Mantine = { baseStats = { hp = 65, attack = 50, defense = 70,
      specialAttack = 80, specialDefense = 140, speed = 70 } },
    Hitmontop = { baseStats = { hp = 50, attack = 95, defense = 95,
      specialAttack = 35, specialDefense = 110, speed = 75 } },
    Entei = { baseStats = { hp = 115, attack = 90, defense = 85,
      specialAttack = 115, specialDefense = 75, speed = 100 } },
  },
}
