#!/usr/bin/env python3
"""conv_marts.py — CL data/items/marts.asm -> marts.lua (dev-side, never shipped).

Parses the Crystal Legacy mart source:
  - constants/mart_constants.asm  -> MART_* constant order (index -> name)
  - data/items/marts.asm          -> `Marts:` pointer table + per-mart item id lists

Output: a plain data table `return { marts = { MART_NAME = { "ITEM", ... }, ... } }`
keyed by MART_* constant name, in MART_* order. Item ids are emitted as the
constant names (which are the Gold engine's item registry ids).

The engine's gen2 marts.lua is `lists` (positional array, 34 entries, martId
indexes into it). CL has 39 marts (37 vanilla + MART_BERRYS + MART_BERRYS_2),
so Phase 2 application decides index mapping — this converter emits the full
name-keyed table.

Usage:
    python3 conv_marts.py CL_SOURCE_DIR OUT_LUA [GOLD_MARTS_LUA]
"""
import re
import sys
from pathlib import Path


def parse_mart_constants(constants_dir: Path) -> list[str]:
    """Return MART_* names in definition order."""
    src = (constants_dir / "mart_constants.asm").read_text()
    names = []
    for m in re.finditer(r"const\s+(MART_\w+)", src):
        names.append(m.group(1))
    return names


def parse_marts_asm(items_dir: Path) -> tuple[list[str], dict[str, list[str]]]:
    """Return (pointer_table_labels, { label: [item_id, ...] })."""
    src = (items_dir / "marts.asm").read_text()
    # pointer table order (dw MartXxx lines following `Marts:`; tab-indented).
    # Labels are CamelCase; `[A-Z]` after "Mart" excludes the `Marts:` header.
    table = []
    for m in re.finditer(r"^\s*dw\s+(Mart[A-Z]\w*)\s*$", src, re.M):
        table.append(m.group(1))
    # per-mart blocks: label MartXxx: ... until the next top-level label
    blocks = {}
    for m in re.finditer(
        r"^(Mart[A-Z]\w*):\s*\n(.*?)(?=^\w+:\s*$|\Z)", src, re.M | re.S
    ):
        label = m.group(1)
        items = []
        for line in m.group(2).splitlines():
            line = line.split(";")[0].strip()
            mm = re.match(r"^db\s+(.+)$", line)
            if not mm:
                continue
            toks = [t.strip() for t in mm.group(1).split(",")]
            if toks == ["-1"]:
                continue  # end marker
            # skip the `db N ; # items` count line and any pure-numeric tokens
            items.extend(t for t in toks if t and not t.isdigit())
        blocks[label] = items
    return table, blocks


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__)
        return 2
    cl_dir = Path(sys.argv[1])
    out_path = Path(sys.argv[2])
    gold_marts = Path(sys.argv[3]) if len(sys.argv) > 3 else None

    constants = parse_mart_constants(cl_dir / "constants")
    table, blocks = parse_marts_asm(cl_dir / "data" / "items")

    # ---- sanity: pointer table count vs constants ----
    print(f"mart constants: {len(constants)}")
    print(f"pointer table:  {len(table)}")
    print(f"mart blocks:    {len(blocks)}")
    if len(table) != len(constants):
        print("WARN: pointer table count != constant count")
    missing = [lbl for lbl in table if lbl not in blocks]
    if missing:
        print(f"ERROR: no block for labels: {missing}")
        return 1
    extra = [lbl for lbl in blocks if lbl not in table]
    if extra:
        print(f"note: blocks not in pointer table: {extra}")  # DefaultMart etc.

    # ---- item id sanity vs gold items registry (if provided) ----
    if gold_marts:
        reg = (gold_marts.parent / "items.lua").read_text()
        all_items = set(re.findall(r'"([A-Z_0-9]+)"', reg))
        missing_items = sorted(
            {i for lbl in table for i in blocks[lbl]} - all_items
        )
        print(f"items not in gold registry: {missing_items or 'NONE'}")

    # ---- emit ----
    lines = [
        "-- Generated by tools/converters/conv_marts.py (dev-side; not shipped).",
        "-- Source: Crystal Legacy data/items/marts.asm",
        "-- Values are Gold item constant ids. Keyed by MART_* name, in MART_* order.",
        "-- NOTE: 39 CL marts vs engine NUM_MARTS=34 (gold); index mapping is a Phase 2 concern.",
        "return {",
        "  marts = {",
    ]
    # pointer table order == MART_* constant order (positional mapping:
    # MART_* names are MART_CHERRYGROVE-style, pointer labels are
    # MartCherrygrove-style — same order, different spelling)
    for i, name in enumerate(constants):
        lbl = table[i] if i < len(table) else None
        items = blocks.get(lbl, []) if lbl else []
        inner = ", ".join(f'"{it}"' for it in items)
        lines.append(f"    {name} = {{ {inner} }},")
    lines.append("  },")
    lines.append("}")
    out_path.write_text("\n".join(lines) + "\n")

    # ---- report ----
    total_items = sum(len(blocks[lbl]) for lbl in table)
    print(f"wrote {out_path}: {len(table)} marts, {total_items} item rows")
    # list marts with >0 items (a mart of zero items is suspicious)
    empties = [
        name for i, name in enumerate(constants)
        if not blocks.get(table[i] if i < len(table) else None, [])
    ]
    print(f"empty marts: {empties or 'NONE'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
