#!/usr/bin/env python3
"""conv_move_tutor.py — CL base_stats tmhm -> tutor_moves.lua
(dev-side, never shipped).

Crystal Legacy's Goldenrod Move Tutor teaches FLAMETHROWER / THUNDERBOLT /
ICE_BEAM for 1000 coins (daily). Learnability is encoded in each species'
`tmhm` line in data/pokemon/base_stats/<species>.asm: CL adds MT01-03 (the
tutor moves) to the tmhm flags of 153 species.

This converter emits one SPECIES list per tutor move, mapping CL base_stats
filenames to engine species registry keys. The filename sets are identical
(modulo sort order): CL uses the same underscore spelling as the engine
(nidoran_f -> NIDORAN_F, farfetch_d -> FARFETCH_D, mr__mime -> MR__MIME,
ho_oh -> HO_OH), so no alias map is needed.

Engine note: we do NOT patch the engine's species.tmhm lists — they are a
LIST of move ids consulted by Breeding (egg-move inheritance) and
ItemEffects, so patching them would leak tutor learnability into eggs.
Gating is done mod-side from this table.

Usage:
    python3 conv_move_tutor.py CL_SOURCE_DIR OUT_LUA
"""
import re
import sys
from pathlib import Path

TUTOR_MOVES = ("FLAMETHROWER", "THUNDERBOLT", "ICE_BEAM")


def parse_tmhm(asm_path: Path) -> list[str]:
    """Return the move tokens on a species' tmhm line (comments stripped)."""
    for line in asm_path.read_text().splitlines():
        if line.lstrip().startswith("tmhm"):
            toks = line.split(";")[0].strip().split()
            return [t.rstrip(",") for t in toks if t != "tmhm"]
    return []


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    cl_root = Path(sys.argv[1])
    out_path = Path(sys.argv[2])

    stats_dir = cl_root / "data" / "pokemon" / "base_stats"
    if not stats_dir.is_dir():
        print(f"ERROR: no base_stats dir at {stats_dir}", file=sys.stderr)
        return 1

    # species -> set of tutor moves learnable
    per_move = {m: [] for m in TUTOR_MOVES}
    counts = {}
    for asm_path in sorted(stats_dir.glob("*.asm")):
        species = asm_path.stem.upper()
        moves = parse_tmhm(asm_path)
        for m in TUTOR_MOVES:
            if m in moves:
                per_move[m].append(species)
        counts[species] = len([m for m in TUTOR_MOVES if m in moves])

    if not any(per_move.values()):
        print("ERROR: no tutor moves found in any tmhm line", file=sys.stderr)
        return 1

    lines = [
        "-- Generated by tools/converters/conv_move_tutor.py (dev-side; not shipped).",
        "-- Source: Crystal Legacy data/pokemon/base_stats/*.asm tmhm lines (MT01-03).",
        "-- Goldenrod Move Tutor learnability: which species can learn each move.",
        "-- Engine note: species.tmhm is a LIST consulted by Breeding/ItemEffects;",
        "-- patching it would LEAK tutor learnability into egg moves. Gate mod-side",
        "-- from this table instead (never patch species.tmhm with these).",
        "return {",
        "  tutor_moves = {",
    ]
    for m in TUTOR_MOVES:
        sps = per_move[m]
        lines.append(f"    {m} = {{")
        for sp in sps:
            lines.append(f"      \"{sp}\",")
        lines.append("    },")
    lines.append("  },")
    lines.append("}")

    # sanity: counts line sums
    sum_counts = sum(len(v) for v in per_move.values())
    lines.append(f"-- species totals: FLAMETHROWER {len(per_move['FLAMETHROWER'])}, "
                 f"THUNDERBOLT {len(per_move['THUNDERBOLT'])}, "
                 f"ICE_BEAM {len(per_move['ICE_BEAM'])}, sum {sum_counts}")

    out_path.write_text("\n".join(lines) + "\n")

    print(f"wrote {out_path}:")
    for m in TUTOR_MOVES:
        print(f"  {m}: {len(per_move[m])} species")
    print(f"  total learnability: {sum_counts}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
