-- Generated by tools/converters/conv_evolutions.py (dev-side; not shipped).
-- Source: Crystal Legacy data/pokemon/evos_attacks.asm
-- FULL CL evolution lists for changed species (pokemon=record semantics:
-- evolutions list replaces wholesale on patch).
-- Rows: { into, item|level|time|comparison (per method), method }
return {
  evolutions = {
    GOLDEEN = {
      { into = "SEAKING", level = 28, method = "EVOLVE_LEVEL" },
    },
    GRAVELER = {
      { into = "GOLEM", level = 38, method = "EVOLVE_LEVEL" },
    },
    HAUNTER = {
      { into = "GENGAR", level = 42, method = "EVOLVE_LEVEL" },
    },
    KADABRA = {
      { into = "ALAKAZAM", level = 42, method = "EVOLVE_LEVEL" },
    },
    MACHOKE = {
      { into = "MACHAMP", level = 38, method = "EVOLVE_LEVEL" },
    },
    ONIX = {
      { into = "STEELIX", item = "METAL_COAT", method = "EVOLVE_ITEM" },
    },
    PINECO = {
      { into = "FORRETRESS", level = 25, method = "EVOLVE_LEVEL" },
    },
    POLIWHIRL = {
      { into = "POLIWRATH", item = "WATER_STONE", method = "EVOLVE_ITEM" },
      { into = "POLITOED", item = "KINGS_ROCK", method = "EVOLVE_ITEM" },
    },
    PORYGON = {
      { into = "PORYGON2", item = "UP_GRADE", method = "EVOLVE_ITEM" },
    },
    SCYTHER = {
      { into = "SCIZOR", item = "METAL_COAT", method = "EVOLVE_ITEM" },
    },
    SEADRA = {
      { into = "KINGDRA", item = "DRAGON_SCALE", method = "EVOLVE_ITEM" },
    },
    SLOWPOKE = {
      { into = "SLOWBRO", level = 37, method = "EVOLVE_LEVEL" },
      { into = "SLOWKING", item = "KINGS_ROCK", method = "EVOLVE_ITEM" },
    },
    SLUGMA = {
      { into = "MAGCARGO", level = 27, method = "EVOLVE_LEVEL" },
    },
    SPINARAK = {
      { into = "ARIADOS", level = 21, method = "EVOLVE_LEVEL" },
    },
    TYROGUE = {
      { into = "HITMONTOP", item = "BRICK_PIECE", method = "EVOLVE_ITEM" },
      { into = "HITMONCHAN", level = 20, comparison = "ATK_LT_DEF", method = "EVOLVE_STAT" },
      { into = "HITMONLEE", level = 20, comparison = "ATK_GT_DEF", method = "EVOLVE_STAT" },
    },
  },
}
